{% set name = "Piexif" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hMatoba/Piexif/archive/{{ version }}.tar.gz
  sha256: abfd9a67795e23d7a76f9407d60841efa68c5d6e43376b295bb821a30602c569

build:
  noarch: python
  number: 4
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
test:
  requires:
    - python {{ python_min }}
  imports:
    - piexif
    - piexif._common
    - piexif._webp
    - piexif.helper

about:
  home: https://github.com/hMatoba/Piexif
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: To simplify exif manipulations with Python. Writing, reading, and more

  description: |
    Piexif simplifies interacting with EXIF data in Python. 
    It includes the tools necessary for extracting, creating, manipulating, 
    converting and writing EXIF data to JPEG, WebP and TIFF files.
  doc_url: https://piexif.readthedocs.io
  dev_url: https://github.com/hMatoba/Piexif

extra:
  recipe-maintainers:
    - mxr-conda
    - agcopenhaver
    - rluria14
    - oblute
